# Generated by Django 5.0.4 on 2024-05-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('sonnyangel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sonnyangel')),
            ],
        ),
    ]
