# Generated by Django 5.0.4 on 2024-05-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonnyangel',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessories'),
        ),
    ]
